#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Data-Munge
Version  : 0.097
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MA/MAUKE/Data-Munge-0.097.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MAUKE/Data-Munge-0.097.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libd/libdata-munge-perl/libdata-munge-perl_0.097-1.debian.tar.xz
Summary  : 'various utility functions'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Data-Munge-man
BuildRequires : perl(Test::Warnings)

%description
Data-Munge
Various utility functions.
INSTALLATION
To install this module, run the following commands:

%package man
Summary: man components for the perl-Data-Munge package.
Group: Default

%description man
man components for the perl-Data-Munge package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Data-Munge-0.097
mkdir -p %{_topdir}/BUILD/Data-Munge-0.097/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Data-Munge-0.097/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Data/Munge.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Data::Munge.3
